version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    # Check the maven registry for updates every day (weekdays)
    schedule:
      interval: "daily"
  - package-ecosystem: "gradle"
    directory: "/"
    # Check the gradle registry for updates every day (weekdays)
    schedule:
      interval: "daily"
